# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{faxijaxy}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eric Saxby", "adamlogic"]
  s.date = %q{2010-06-30}
  s.description = %q{jquery.form requires that :js and :json file upload forms have their responses wrapped in textarea tags. This gem builds on the jaxy_file_uploads by adamlogic to add that support to Rails 3.}
  s.email = %q{sax@livinginthepast.org}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.textile"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "Gemfile",
     "LICENSE",
     "README.textile",
     "Rakefile",
     "VERSION",
     "faxijaxy.gemspec",
     "init.rb",
     "lib/faxijaxy.rb",
     "lib/faxijaxy/railtie.rb",
     "rails/init.rb",
     "test/helper.rb",
     "test/test_faxijaxy.rb"
  ]
  s.homepage = %q{http://github.com/sax/faxijaxy}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Add jquery.form support to Rails 3}
  s.test_files = [
    "test/helper.rb",
     "test/test_faxijaxy.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.0.0.beta4"])
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<rails>, [">= 3.0.0.beta4"])
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.0.0.beta4"])
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

